title: "shimewtr Blog"
description: >
  Webエンジニアshimewtrのブログです。日々の感想を投稿していきます。
baseurl:
url: "https://blog.shimewtr.me"

excerpt_separator: "<!--more-->"

author:
  name: shimewtr
  github: shimewtr
  twitter: shimewtr

google_analytics_id: G-R8K2DVFSPL

google_site_verification: EYEKdiEFJWoAOki

sass:
  style: compressed

plugins:
  - jekyll-archives
  - jekyll-paginate
  - jekyll-sitemap

paginate: 10
paginate_path: page:num

jekyll-sitemap:
  url: "https://blog.shimewtr.me"
jekyll-archives:
  enabled:
    - tags
  layouts:
    tag: archive
  permalinks:
    tag: "/archives/tag/:name/"
