title: My Blog
description: >
  My Blog Description. This Theme is Louis.
baseurl: ""
url: ""

excerpt_separator: "<!--more-->"

author:
  name: John Smith
  email: john.smith@example.com
  github: jekyll
  twitter: jekyll

sass:
  style: compressed

plugins:
  - jekyll-paginate

paginate: 10
paginate_path: page:num
