title: My Blog
description: >
  My Blog Description. This Theme is Louis.
baseurl: ""
url: ""

excerpt_separator: "<!--more-->"

author:
  name: John Smith
  github: jekyll
  twitter: jekyll
  facebook: jekyll

google_analytics_id:

sass:
  style: compressed

plugins:
  - jekyll-archives
  - jekyll-paginate
  - jekyll-sitemap

paginate: 10
paginate_path: page:num

jekyll-archives:
  enabled:
    - tags
  layouts:
    tag: archive
  permalinks:
    tag: "/archives/tag/:name/"
