title: My Blog
description: >
  My Blog Description. This Theme is Louis.
baseurl: ""
url: ""

excerpt_separator: "<!--more-->"

author:
  name: John Smith
  github: jekyll
  twitter: jekyll
  facebook: jekyll

sass:
  style: compressed

plugins:
  - jekyll-paginate

paginate: 5
paginate_path: page:num
