name: Publish Gem

on:
  push:
    tags:
      - 'v*'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@master

    - name: Set up Ruby
      uses: actions/setup-ruby@v1
      with:
        ruby-version: '2.6'

    - name: Publish to RubyGems
      env:
        RUBYGEMS_TOKEN: ${{secrets.RUBYGEMS_TOKEN}}
      run: |
        mkdir -p $HOME/.gem
        touch $HOME/.gem/credentials
        chmod 600 $HOME/.gem/credentials
        echo "---" > $HOME/.gem/credentials
        echo ":rubygems_api_key: ${RUBYGEMS_TOKEN}" >> $HOME/.gem/credentials
        rake release

