name: Publish Gem

on:
  push:
    tags:
      - 'v*'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@master

    - name: Set up Ruby
      uses: actions/setup-ruby@v1
      with:
        ruby-version: '2.6'

    - name: Setup Release Credentials
      env:
        GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}
      run: |
        mkdir -p $HOME/.gem
        touch $HOME/.gem/credentials
        chmod 600 $HOME/.gem/credentials
        echo "---" >$HOME/.gem/credentials
        echo ":github: Bearer ${GITHUB_TOKEN}" >> $HOME/.gem/credentials

    - name: Publish Gem to GitHub Packages
      run: |
        export OWNER=$( echo ${{ github.repository }} | cut -d "/" -f 1 )
        gem build *.gemspec
        gem push --KEY github --host https://rubygems.pkg.github.com/${OWNER} *.gem
